POST http://localhost:8091/ft/sys-bank/bankall
Content-Type: application/json
token:f390ff663cacbb263803e3bdaa6451f1

{
  "type":"2"
}

###
POST http://localhost:8091/ft/sys-bank/updateBank
Content-Type: application/json
token:f390ff663cacbb263803e3bdaa6451f1

{
  "id":"1",
  "cusId": "5"
}

###
POST http://localhost:8091/ft/sys-bank/addBank
Content-Type: application/json
token:f390ff663cacbb263803e3bdaa6451f1

{
  "cusId": 2,
  "bankName": "山东太原中国银行分行",
  "shortName": "骆家庄建设银行",
  "account": "11111111",
  "type": "2",
  "nature": "4",
  "balance": "0"
}

###
POST http://localhost:8091/ft/sys-bank/deleteByIds/1
Content-Type: application/json
token:f390ff663cacbb263803e3bdaa6451f1

{}
###
