POST http://localhost:8091/ft/sys-bank/query
Content-Type: application/json
token:29c156be8d9e66da23d110815e6f026b

{
  "cusId": "2194",
  "pageSize": 1
}

###
POST http://localhost:8091/ft/sys-bank/updateBank
Content-Type: application/json
token:f390ff663cacbb263803e3bdaa6451f1

{
  "id":"1",
  "cusId": "5"
}

###
POST http://localhost:8091/ft/sys-bank/addBank
Content-Type: application/json
token:ae4b6e1340cd50474e99e2d4b4d966d7

{
  "cusId":8,
  "code": "xsaaa",
  "bankName": "山东太原中国银行分行",
  "shortName": "太原银行",
  "account": "1234474X848",
  "area": "1",
  "type": "3",
  "nature": "5",
  "belongTo": "4",
  "balance": "78.45"
}

###
POST http://localhost:8091/ft/sys-bank/deleteByIds/1
Content-Type: application/json
token:f390ff663cacbb263803e3bdaa6451f1

{}
###
