###
POST http://localhost:8091/ft/sys/base-data/queryCity
Content-Type: application/json
token:d58d894073090e6f1d0c72d95e381055

{
  "dataId": "1"
}

###
POST http://localhost:8091/ft/sys/base-data/query
Content-Type: application/json
token:d58d894073090e6f1d0c72d95e381055

{}

###
### POST http://192.168.3.222:8091/ft/sys/login/admin/1
POST http://localhost:8091/ft/sys/login/admin/1
Content-Type: application/json

{}
