POST http://localhost:8091/ft/sys/base-data/queryCity
Content-Type: application/json
token:d088456100d3328694b5d087337b58bf

{
  "isMunicipality": "false",
  "depth": 1
}

###
POST http://localhost:8091/ft/sys/base-data/query
Content-Type: application/json
token:bd1f683fb8b7de0638bfd7d534b5a137

{}

###
### POST http://192.168.3.222:8091/ft/sys/login/admin/1
POST http://localhost:8091/ft/sys/login/admin/1
Content-Type: application/json

{}
