POST http://localhost:8091/ft/bdm-customer/export
Content-Type: application/json
token:28545823f7fbe4cd0550a212b6c2169c

{
  "ids": [
    1,
    2,
    3,
    4,
    5,
    8,
    9,
    7,
    8
  ],
  "condition": "HNCB339"
}

###
###
POST http://localhost:8091/ft/bdm-customer/delete
Content-Type: application/json
token:b778d40a6c24814aa1197ad7da83b7c7

{
  "ids": [
    1,2
  ]
}

###
POST http://localhost:8091/ft/bdm-customer/update
Content-Type: application/json
token:bd1f683fb8b7de0638bfd7d534b5a137

{
  "id": 1,
  "name": "上海五锐金属集团有限公司_UPDATE",
  "banks": [
    {
      "id": 17,
      "bankFullName": "银行名称1修改",
      "shortName": "银行简称1",
      "accountBalance": "100.22",
      "bankAccount": "aaaaaaa",
      "areaType": "0",
      "bankName": "0",
      "accountStyle": "0",
      "accountType": "0"
    },
    {
      "bankFullName": "银行名称2",
      "shortName": "银行简称2",
      "accountBalance": "99.99",
      "bankAccount": "bbbbbbb",
      "areaType": "1",
      "bankName": "1",
      "accountStyle": "0",
      "accountType": "1"
    }
  ]
}

###
POST http://localhost:8091/ft/bdm-customer/add
Content-Type: application/json
token:bd1f683fb8b7de0638bfd7d534b5a137

{

  "name": "测试更新客商",
  "code": "UPDATETEST",
  "shortname": "测试更新客商简称",
  "type": "1",
  "area": "上海",
  "banks": [
    {
      "cusId": "1",
      "code": "12222",
      "bankName": "银行名称1",
      "shortName": "银行简称1",
      "account": "1111111",
      "type": 0,
      "nature": 0,
      "balance": 111.11,
      "belongTo": 1
    },
    {
      "cusId": "1",
      "bankName": "银行名称12",
      "shortName": "银行简称12",
      "account": "11111112",
      "type": 0,
      "nature": 0,
      "balance": 111.11,
      "belongTo": 1
    }
  ]
}

###
POST http://localhost:8091/ft/bdm-customer/query
Content-Type: application/json
token:b778d40a6c24814aa1197ad7da83b7c7

{
  "id": "1"
}

###
