POST http://localhost:8091/ft/storage-expense-type/delete/27
Content-Type: application/json
token:ea9246c1df9c4b78456ec20bc61cc6b5

{}

###
POST http://localhost:8091/ft/storage-expense-type/add
Content-Type: application/json
token:ea9246c1df9c4b78456ec20bc61cc6b5

{
  "code": "030",
  "name": "物业管理费"
}

###
POST http://localhost:8091/ft/storage-expense-type/update
Content-Type: application/json
token:ea9246c1df9c4b78456ec20bc61cc6b5

{
  "id": "2",
  "code": "025"
}

###
//理货费
POST http://localhost:8091/ft/storage-expense-type/query
Content-Type: application/json
token:ea9246c1df9c4b78456ec20bc61cc6b5

{}

###

