POST http://localhost:8091/ft/bdm-warehouse/delete_warehouse/58
Content-Type: application/json
token:254c137aa57c8d64f9b6abac59962b2b

{}

###
POST http://localhost:8091/ft/bdm-warehouse/update_warehouse
Content-Type: application/json
token:254c137aa57c8d64f9b6abac59962b2b

{
  "id":"17",
  "personCharge": "夏宗粹",
  "phone": "021-51642507"
}

###
POST http://localhost:8091/ft/bdm-warehouse/get_warehousetree
Content-Type: application/json
token:254c137aa57c8d64f9b6abac59962b2b

{}

###
POST http://localhost:8091/ft/bdm-warehouse/add_warehouse
Content-Type: application/json
token:254c137aa57c8d64f9b6abac59962b2b

{
  "parentId": 1,
  "code": "SGWL001",
  "cusId": 1,
  "personCharge": "张三",
  "phone": "1516545",
  "name": "上海上港库",
  "isVirtual": 0
}

###
POST http://localhost:8091/ft/bdm-warehouse/query/58
Content-Type: application/json
token:254c137aa57c8d64f9b6abac59962b2b

{}

###
