POST http://localhost:8091/ft/bdm-warehouse/delete
Content-Type: application/json
token:8df2a985d934df55222a7d62c3c99024

{
  "ids":[59,60]
}

###
POST http://localhost:8091/ft/bdm-warehouse/update
Content-Type: application/json
token:8df2a985d934df55222a7d62c3c99024

{
  "id":"59",
  "personCharge": "夏宗粹",
  "phone": "021-51642507"



}

###
POST http://localhost:8091/ft/bdm-warehouse/queryList
Content-Type: application/json
token:8df2a985d934df55222a7d62c3c99024

{}

###
POST http://localhost:8091/ft/bdm-warehouse/add
Content-Type: application/json
token:8df2a985d934df55222a7d62c3c99024

{
  "code": "SGWL001",
  "cusId": 1,
  "personCharge": "李四",
  "phone": "1516545",
  "name": "上海上港库",
  "isVirtual": 0
}

###
