POST http://localhost:8091/ft/bdm-cargo-month-price/querycargo/4
Content-Type: application/json
token:8df2a985d934df55222a7d62c3c99024

{}

###
POST http://localhost:8091/ft/bdm-cargo-month-price/add_monthprice
Content-Type: application/json
token:8df2a985d934df55222a7d62c3c99024

{
  "cargoCategoryId":4,
  "marchPrice": "30"
}

###
