POST http://localhost:8091/ft/sys-cargo-category/add_cargocategory
Content-Type: application/json
token:0543a30aa72698a7671155d514b2a1a5

{
  "categoryName": "碳块",
  "categoryCode": "13",
  "parentPkid": "1"
}

###
POST http://localhost:8091/ft/sys-cargo-category/update_cargocategory
Content-Type: application/json
token:0543a30aa72698a7671155d514b2a1a5

{
  "id": "3",
  "categoryName": "铝块"
}

###
POST http://localhost:8090/ft/sys-categoryName-category/query/2
Content-Type: application/json
token:9b36081de640c644d45483241becd0a9

{}

###
POST http://localhost:8090/ft/sys-cargo-category/del/1
Content-Type: application/json
token:9b36081de640c644d45483241becd0a9

{}

###
POST http://localhost:8090/ft/sys-cargo-category/getSysCargoTypeTree
Content-Type: application/json
token:9b36081de640c644d45483241becd0a9

{}

###
