POST http://localhost:8090/ft/sys-cargo-info/getCargoList
Content-Type: application/json
token:1e299919ed4cd5a3625ee0f50c0f8077


{}

###
POST http://localhost:8090/ft/sys-cargo-info/delCargoInfo/1,2
Content-Type: application/json
token:1e299919ed4cd5a3625ee0f50c0f8077


{}

###
POST http://localhost:8090/ft/sys-cargo-info/addCargoInfo
Content-Type: application/json
token:1e299919ed4cd5a3625ee0f50c0f8077

{"cargoCode": "LD67","cargoName": "铁石","categoryPkid": "4","cargoUnit": "2"}

###
POST http://localhost:8090/ft/sys-cargo-info/updaCargoInfo
Content-Type: application/json
token:1e299919ed4cd5a3625ee0f50c0f8077

{"id": "5","aluminumPlant": "常山铁龙","specification": "178*5.8","brand": "铁龙","cargoName": "铁石"}
###
POST http://localhost:8090/ft/sys-cargo-info/getSysCargoInfo
Content-Type: application/json
token:1e299919ed4cd5a3625ee0f50c0f8077

{"keyWord": "扁锭"}

###
