POST http://localhost:8091/ft/bdm-cargo-info/update
Content-Type: application/json
token:f7cea56c5efb218ffe3b55e00dc356e0

{"id":218,"": "铝锭"}

###
POST http://localhost:8091/ft/bdm-cargo-info/add
Content-Type: application/json
token:f7cea56c5efb218ffe3b55e00dc356e0

{
  "cargoCode": "1615",
  "cargoName": "金块",
  "categoryPkid": 3,
  "flagCargoInventory":1
}

###
POST http://localhost:8091/ft/bdm-cargo-info/delete/218,217
Content-Type: application/json
token:f7cea56c5efb218ffe3b55e00dc356e0

{}

###
POST http://localhost:8091/ft/bdm-cargo-info/get_cargoinfo
Content-Type: application/json
token:f7cea56c5efb218ffe3b55e00dc356e0

{
  "keyWord":"金块"
}
###

