POST http://localhost:8091/ft/sys-company/add
Content-Type: application/json
token:d088456100d3328694b5d087337b58bf

{
  "acronym": "TEST",
  "name": "测试公司",
  "shortName": "测试公司简称",
  "contactUser": "contactUser",
  "province": "1",
  "city": "1",
  "district": "1",
  "address": "address",
  "mobile": "mobile"
}

###
POST http://localhost:8091/ft/sys-company/update
Content-Type: application/json
token:8c9c61578e2493b03216123038610a26

{"comCode": "中文"}

###
###
GET http://localhost:8091/ft/sys-company/get?id=0
Accept: application/json
token:8c9c61578e2493b03216123038610a26

###
POST http://localhost:8090/ft/sys-company/get_com
Content-Type: application/json
token:1e299919ed4cd5a3625ee0f50c0f8077

{}

###POST http://192.168.3.222:8091/ft/sys-company/get_fuzzy/
POST http://localhost:8091/ft/sys-company/get_fuzzy/
Content-Type: application/json

{"username": "admin","shortname": "xfy"}

###
POST http://localhost:8091/ft/sys-company/delete
Content-Type: application/json
token:6785e990c71c3f8a2c528d9a5eaa9ef0

{"ids": [415,416]}

###
POST http://localhost:8088/ft/sys-company/add_update_com
Content-Type: application/json

{
  "id": 286,
  "addUpdate": "update",
  "comCode": "LNHTSY",
  "comName": "测试添加公司",
  "shortComName": "测试",
  "contactUser": "1",
  "province": "河北",
  "city": "石家庄",
  "district": "藁城",
  "address": "世纪街",
  "parentId": "",
  "mobile": "",
  "createdTime": "2020-07-21T09:27:03",
  "updatedBy": 1,
  "updatedTime": "2020-07-21T09:27:03"
}

###
POST http://localhost:8091/ft/sys-company/get_fuzzy/
Content-Type: application/json

{"shortname": "sh"}

###
POST http://localhost:8091/ft/sys-company/get_by_wrapper
Content-Type: application/json
token:c0e58c4297fdbc82918ff6c3a9f373f3

{"currentPage": 1,"acronym": "003"}

###
### POST http://192.168.3.222:8091/ft/sys/login/admin/1
POST http://localhost:8091/ft/sys/login/admin/1
Content-Type: application/json

{}
