POST http://localhost:8091/ft/sys-dictionary/delete_dictionary
Content-Type: application/json
token:bf61792791c22d64ac205cffd48109c8

{"ids": "55"}

###
POST http://localhost:8091/ft/sys-dictionary/update_dictionary
Content-Type: application/json
token:ea9246c1df9c4b78456ec20bc61cc6b5

{
  "id":196,
  "createdBy":4,
  "createdTime":"2020-12-04 16:46:34",
  "updatedBy":4,
  "updatedTime":"2020-12-04 16:46:35",
  "deleted":0,
  "name":"sadasdds",
  "des":"描述11",
  "value":"",
  "pid":null
}

###
POST http://localhost:8091/ft/sys-dictionary/add_dictionary
Content-Type: application/json
token:2def66623b4e7d6c375beb9b619e78fa

{"name": "TEST_ADD","des": "添加描述","children":[] }

###
POST http://localhost:8091/ft/sys-dictionary/get_dictionary_children
Content-Type: application/json
token:bf61792791c22d64ac205cffd48109c8

{"id": "37"}

###
POST http://localhost:8091/ft/sys-dictionary/get_dictionary_page
Content-Type: application/json
token:f7cea56c5efb218ffe3b55e00dc356e0

{"currentPage": "2","pageSize": 10}

###
