POST http://localhost:8088/ft/sys-needs/reply/queryOne/1
Content-Type: application/json
token:6e4133bb3eecf01f0ce45dad6be64700

{}

###
POST http://81.68.92.240:8088/ft/sys-needs/reply/delete/1,2
Content-Type: application/json
token:9e5f10109421ac53c66215b9b61669f2

{}

###
POST http://81.68.92.240:8088/ft/sys-needs/reply/update
Content-Type: application/json
token:9e5f10109421ac53c66215b9b61669f2

{"id":"1","parentId": "","content": "我是测试修改系统需求回复"}

###
POST http://81.68.92.240:8088/ft/sys-needs/reply/add
Content-Type: application/json
token:9e5f10109421ac53c66215b9b61669f2

{"needId": "1","parentId": "3","content": "我是测试二级菜单02"}

###
POST http://localhost:8088/ft/sys-needs/delete/3,4
Content-Type: application/json
token:ce3154b37d691919685abc1f717d1402

###
POST http://localhost:8088/ft/sys-needs/update
Content-Type: application/json
token:6e4133bb3eecf01f0ce45dad6be64700

{"id":4,"title":"我是测试修改系统需求标题00","handler": "1"}

###
POST http://localhost:8088/ft/sys-needs/add
Content-Type: application/json
token:6e4133bb3eecf01f0ce45dad6be64700

{"title":"我是测试添加系统需求标题02","content": "我是测试添加系统需求内容"}

###
POST http://localhost:8088/ft/sys-needs/queryPage
Content-Type: application/json
token:6e4133bb3eecf01f0ce45dad6be64700

{"endDateTime": "2020-11-03"}
### 81.68.92.240
POST http://81.68.92.240:8088/ft/sys/login/admin/1
Content-Type: application/json

###
