POST http://localhost:8091/ft/run-rise-price/updateRunRisePrice
Content-Type: application/json
token:773649c52e20abd4cb6c3332b1095f7c

{}

###
POST http://localhost:8091/ft/run-rise-price/queryRunRisePage
Content-Type: application/json
token:773649c52e20abd4cb6c3332b1095f7c

{"condition": "上海","pageSize": 1}

###