POST http://localhost:8091/ft/sys/user/user_in_dept
Content-Type: application/json
token:78802a2d37844c7b922e44d0f2b57f76

{
  "currentPage": 1,
  "pageSize": 10,
  "deptId": [-1,1,2,3,4,5,6,7,8,9,10,2035]
}


###
POST http://localhost:8090/ft/sys/login/admin/1
Content-Type: application/json

{}

###
POST http://localhost:8088/api/item
Content-Type: application/json

{}

###
POST http://localhost:8088/ft/sys-company/get_by_wrapper
Content-Type: application/json

{
  "name": "上海鑫抚源"
}

###
POST http://localhost:8088/ft/sys-department/addDept
Content-Type: application/json

{
  "comId": "1",
  "deptname": "11111",
  "parentId": "2"
}

###
POST http://localhost:8088/ft/sys/testId
Content-Type: application/json

{}

###
POST http://localhost:8090/ft/sys/logout
Content-Type: application/json
token:3ea639567f339845dd7dedcc3de5098f

###
POST http://localhost:8090/ft/sys-company/get_fuzzy/admin/sh
Content-Type: application/json
token:efdb271e9c30caf4c450e1c68fdf41ec

{}

###
POST http://localhost:8091/ft/sys/login/admin/1
Content-Type: application/json

{}

###
POST http://localhost:8088/ft/sys/signup
Content-Type: application/json

{
  "username": "admin",
  "password": "1",
  "gender": "0",
  "realname": "管理员"
}

###
