POST http://localhost:8088/ft/sys-company/get_by_wrapper
Content-Type: application/json

{"name":"上海鑫抚源"}

###
POST http://localhost:8088/ft/sys-department/addDept
Content-Type: application/json

{"comId": "1","deptname": "11111","parentId": "2"}

###
POST http://localhost:8088/ft/sys/testId
Content-Type: application/json

{}

###
POST http://localhost:8088/ft/sys/logout
Content-Type: application/json
token:5531b55s465851f730f3f4983cebe998d


###
POST http://localhost:8088/ft/sys/login/admin/1
Content-Type: application/json

{}

###
POST http://localhost:8088/ft/sys/signup
Content-Type: application/json

{"username": "admin","password": "1","gender": "0","realname": "管理员"}

###
